management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:account-db
  cloud:
    discovery:
      enabled: 'true'
    config:
      enabled: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: 'true'
account:
  params:
    a: '33'
    b: '44'