# management:
#   endpoints:
#     web:
#       exposure:
#         include: '*'
# spring:
#   h2:
#     console:
#       enabled: 'true'
#   cloud:
#     discovery:
#       enabled: 'true'
#     config:
#       enabled: 'true'
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka
#   instance:
#     prefer-ip-address: 'true'
# global:
#   params:
#     p2: '3333'
#     p1: '333'
